### ISSUE TITLE
Verify it works with all plugins

### ISSUE THREAD

**Issue by ekohl** [theforeman/actions#1]
* [x] https://github.com/Katello/katello/pull/10780
* [x] https://github.com/RedHatSatellite/foreman_theme_satellite/pull/2
* [ ] https://github.com/dm-drogeriemarkt/foreman_dlm/pull/66
* [ ] https://github.com/dm-drogeriemarkt/foreman_rescue/pull/25
* [x] https://github.com/theforeman/foreman-tasks/pull/677
* [x] https://github.com/theforeman/foreman_ansible/pull/519
* [x] https://github.com/theforeman/foreman_azure_rm/pull/183
* [x] https://github.com/theforeman/foreman_bootdisk/pull/152
* [ ] https://github.com/theforeman/foreman_default_hostgroup/pull/62
* [x] https://github.com/theforeman/foreman_discovery/pull/613
* [x] https://github.com/theforeman/foreman_expire_hosts/pull/75
* [x] https://github.com/theforeman/foreman_fog_proxmox/pull/311
* [x] https://github.com/theforeman/foreman_google/pull/66
* [x] https://github.com/theforeman/foreman_hooks/pull/64
* [x] https://github.com/theforeman/foreman_host_extra_validator/pull/14
* [x] https://github.com/theforeman/foreman_kubevirt/pull/153
* [x] https://github.com/theforeman/foreman_leapp/pull/133
* [x] https://github.com/theforeman/foreman_monitoring/pull/95
* [x] ~https://github.com/theforeman/foreman_omaha/pull/66~
* [x] https://github.com/theforeman/foreman_openscap/pull/548
* [x] https://github.com/theforeman/foreman_puppet/pull/381
* [x] https://github.com/theforeman/foreman_remote_execution/pull/863
* [x] https://github.com/theforeman/foreman_rh_cloud/pull/866
* [x] https://github.com/theforeman/foreman_salt/pull/192
* [x] ~https://github.com/theforeman/foreman_setup/pull/50~
* [x] https://github.com/theforeman/foreman_templates/pull/180
* [x] https://github.com/theforeman/foreman_webhooks/pull/71
* [x] https://github.com/theforeman/puppetdb_foreman/pull/83
* [x] https://github.com/theforeman/foreman_kernel_care/pull/64

**Comment by ekohl** [comment]
At least foreman_dlm does something extra that's not captured yet: precompile the assets in a production environment:
https://github.com/dm-drogeriemarkt/foreman_dlm/blob/56af16ae462e5216054473432826cfa235ff26e3/.github/workflows/ci.yml#L77-L84

It also uses `nick-fields/retry@v2` to retry failing tests.

**Comment by ekohl** [comment]
Another thing that is missing is the caching only step on push. This would be to just install the gems, which builds a cache. If that's done when pushing to master, all PRs can benefit the cache. Otherwise the cache is stored in the PR owners repo.

**Comment by ekohl** [comment]
Another note to self:
* NPM caching: https://github.com/actions/setup-node#caching-packages-dependencies
* Only install npm if `package.json` exists

**Comment by ofedoren** [comment]
Just to update plugins list: https://github.com/theforeman/foreman_webhooks

**Comment by ekohl** [comment]
Thanks. I found the list by doing `ls ~/dev/foreman_*/.github/workflows` so it looks like locally I don't have it checked out.

**Comment by ekohl** [comment]
More notes to self: `github.head_ref` is only available in the PR context, not on push.

**Comment by ekohl** [comment]
REX also has:
```yaml
      - name: 'Upload logs'
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: logs
          path: log/*.log
          retention-days: 5
```

**Comment by ekohl** [comment]
`foreman_ansible` has the same log upload and also has `rake webpack:compile`.

**Comment by archanaserver** [comment]
https://github.com/theforeman/foreman_salt/pull/192

**Comment by ekohl** [comment]
In light of https://community.theforeman.org/t/convert-foreman-plugins-continuous-integration-to-github-actions/35917 I've expanded the list with all plugins shipped in Satellite and those currently testing in Jenkins. It already included all plugins that had previous actions.

**Comment by adamruzicka** [comment]
:green_circle: https://github.com/theforeman/foreman_remote_execution/pull/863

**Comment by adamruzicka** [comment]
https://github.com/theforeman/foreman_webhooks/pull/71

**Comment by ofedoren** [comment]
https://github.com/theforeman/foreman_templates/pull/180

**Comment by archanaserver** [comment]
https://github.com/theforeman/foreman_discovery/pull/613

**Comment by archanaserver** [comment]
https://github.com/theforeman/foreman_omaha/pull/66
https://github.com/theforeman/foreman_monitoring/pull/95

**Comment by archanaserver** [comment]
https://github.com/theforeman/foreman_setup/pull/50

**Comment by archanaserver** [comment]
https://github.com/theforeman/puppetdb_foreman/pull/83

**Comment by archanaserver** [comment]
https://github.com/theforeman/foreman_google/pull/66

**Comment by archanaserver** [comment]
https://github.com/dm-drogeriemarkt/foreman_dlm/pull/66
https://github.com/dm-drogeriemarkt/foreman_rescue/pull/25

**Comment by archanaserver** [comment]
https://github.com/theforeman/foreman_host_extra_validator/pull/14

**Comment by archanaserver** [comment]
https://github.com/theforeman/foreman_hooks/pull/64

**Comment by archanaserver** [comment]
https://github.com/theforeman/foreman_default_hostgroup/pull/62
https://github.com/theforeman/foreman_host_extra_validator/pull/14

**Comment by archanaserver** [comment]
Dropping this here, to keep everything on track: https://github.com/theforeman/actions/issues/38

**Comment by dosas** [comment]
https://github.com/theforeman/foreman_maintain

**Comment by ekohl** [comment]
> https://github.com/theforeman/foreman_maintain

This is not Foreman plugin, even though the name implies it so the Foreman plugin workflow doesn't apply.

**Comment by ekohl** [comment]
Closing since it's implemented for the majority. https://github.com/orgs/theforeman/projects/10/views/1 tracks what's remaining now.
