### ISSUE TITLE
Add Support for setup-chromedriver  step

### ISSUE THREAD

**Issue by archanaserver** [theforeman/actions#38]
In foreman_puppet we have a workflow step executed, `setup chromedrive` https://github.com/theforeman/foreman_puppet/blob/master/.github/workflows/ruby_tests.yml#L47-L48. Unfortunately, our reusable workflow currently lacks support for this specific step.

For reference: https://github.com/theforeman/foreman_puppet/pull/381#discussion_r1448640800

**Comment by ekohl** [comment]
The 22.04 runner already includes this: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#browsers-and-drivers
