### ISSUE TITLE
Support setting arbitrary environment variables in foreman_plugin 

### ISSUE THREAD

**Issue by laugmanuel** [theforeman/actions#44]
We should support setting arbitrary environment variables by passing them as an input to the job.
This would allow the caller/user to customize the test behaviour by reading the variables back in code.

See discussion in https://github.com/dm-drogeriemarkt/foreman_wreckingball/pull/113

**Comment by laugmanuel** [comment]
@ekohl, @evgeni any feedback on the request?

**Comment by evgeni** [comment]
The request is valid, we just didn't have time to think about it further.

**Comment by laugmanuel** [comment]
@evgeni I've prepared a PR for this feature.
It looks a bit hacky as I didn't find another way of passing information from caller to the reusable workflow. Passing env directly is a limitation stated here: https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations
